apiVersion: v1
kind: Pod
metadata:
  name: kustomization-file
spec:
  containers:
  - image: busybox:1.28
    name: kustomization-file
    command:
      - sleep
      - "3600"
    volumeMounts:
      - name: kustomization-file
        mountPath: /etc/kustomzation-file
        readOnly: true
  volumes:
    - name: kustomization-file
      secret:
        secretName: db-user-pass-file-2md6gt522g


