apiVersion: v1
kind: Pod
metadata:
  name: base64
spec:
  containers:
  - image: busybox:1.28
    name: base64
    command:
      - sleep
      - "3600"
    volumeMounts:
      - name: base64
        mountPath: /etc/base64-secret
        readOnly: true
  volumes:
    - name: base64
      secret:
        secretName: secret-base64


