apiVersion: v1
kind: Pod
metadata:
  name: base64-var
spec:
  containers:
  - image: busybox:1.28
    name: base64
    command:
      - sleep
      - "3600"
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: secret-base64
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secret-base64
            key: password


