kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: harbor-repo-harbor-chartmuseum
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: nfs-storageclass