apiVersion: v1
kind: Pod
metadata:
  name: qos-demo
  namespace: task
spec:
  containers:
  - name: qos-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "200Mi"
        cpu: "100m"
      requests:
        memory: "200Mi"
        cpu: "100m"